version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      docker:
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: no
          MYSQL_ROOT_PASSWORD: 'password'
          MYSQL_DATABASE: etsy
          MYSQL_ROOT_HOST: 127.0.0.1
          MYSQL_USER: root
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run:
                command: npm test
                no_output_timeout: 3m
            - run:
                name: Install dependencies and run tests
                command: |
                  mysql -u root -p
workflows:
    build-and-test:
      jobs:
        - build-and-test
