version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run:
                command: npm test
                no_output_timeout: 3m
            - run:
                name: Install dependencies and run tests
                command: mysql -u root -p
workflows:
    build-and-test:
      jobs:
        - build-and-test
